version: '3'


# here we add restart also delete name and profile

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=express-docker
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    # if there any problems (crash , failure , etc) will restart
    restart: always


  app:
    # to take image go to github => packages => your package created for it
    image: ghcr.io/ibrahimzeer/express-docker:$GIT_VERSION
    restart: always
    container_name: express-docker
    build: .
    environment:
      - PORT=80
      # mysql can be such as domain name
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=express-docker
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data: