name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    # create edits in github tokens
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set image version (tag)
        id: image_version
        run: echo "gitsha=$(git rev-parse --short HEAD )" >> $GITHUB_OUTPUT
      # we add this to create publish and use it
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run:
          docker build . --file Dockerfile --tag ghcr.io/ibrahimzeer/express-docker:${{ steps.image_version.outputs.gitsha }}
          #should to be tag name same name of repo
      - name: Publish docker image
        run: docker push ghcr.io/ibrahimzeer/express-docker:${{ steps.image_version.outputs.gitsha }}
      # set as environment variable to change comunication chanle
      - name: configure docker host
        uses: khaledez/configure-docker-host@v1
        with:
          host: 3.9.10.219
          user: github
          ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}
      - name: deploy
        run: docker compose -f docker-compose-prod.yml up -d
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: pring logs
        if: always()
        run: docker
