name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    # create edits in github tokens
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # we add this to create publish and use it
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run:
          docker build . --file Dockerfile --tag ghcr.io/ibraheemzeer/express-app:$(date +%s)
          #should to be tag name same name of repo
